default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: "8732328"

development:
  <<: *default
  database: proyectCATEC
  username: postgres
  password: "8732328"
  host: localhost
  port: 5432

test:
  <<: *default
  database: proyectCATEC_test
  username: postgres
  password: "8732328"
  host: localhost
  port: 5432

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>